name: icloud-for-linux
version: '0.21'
summary: iCloud for Linux
description: iCloud for Linux

grade: stable
confinement: strict
base: core20

parts:
  icloud-for-linux:
    plugin: cmake
    source: .
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr

apps:
  mail:
    command: usr/bin/icloud-for-linux mail Mail
    extensions: &extensions
      - gnome-3-38
    plugs: &plugs
      - browser-support
      - desktop
      - desktop-legacy
      - home
      - network
      - network-status
      - opengl
      - screen-inhibit-control
      - wayland
      - x11
    environment: &environment
      TMPDIR: $XDG_RUNTIME_DIR
  contacts:
    command: usr/bin/icloud-for-linux contacts Contacts
    extensions: *extensions
    plugs: *plugs
    environment: *environment
  calendar:
    command: usr/bin/icloud-for-linux calendar Calendar
    extensions: *extensions
    plugs: *plugs
    environment: *environment
  photos:
    command: usr/bin/icloud-for-linux photos Photos
    extensions: *extensions
    plugs: *plugs
    environment: *environment
  drive:
    command: usr/bin/icloud-for-linux iclouddrive Drive
    extensions: *extensions
    plugs: *plugs
    environment: *environment
  notes:
    command: usr/bin/icloud-for-linux notes Notes
    extensions: *extensions
    plugs: *plugs
    environment: *environment
  reminders:
    command: usr/bin/icloud-for-linux reminders Reminders
    extensions: *extensions
    plugs: *plugs
    environment: *environment
  pages:
    command: usr/bin/icloud-for-linux pages Pages
    extensions: *extensions
    plugs: *plugs
    environment: *environment
  numbers:
    command: usr/bin/icloud-for-linux numbers Numbers
    extensions: *extensions
    plugs: *plugs
    environment: *environment
  keynote:
    command: usr/bin/icloud-for-linux keynote Keynote
    extensions: *extensions
    plugs: *plugs
    environment: *environment
  find:
    command: usr/bin/icloud-for-linux find Find
    extensions: *extensions
    plugs: *plugs
    environment: *environment
